name: CI

on:
  workflow_call:

jobs:
  base_source_checks:
    name: "Base source checks"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '>=3.12'

      - uses: pre-commit/action@v3.0.1


  tests:
    name: "${{ matrix.imagename }} -- ${{ matrix.machine }} -- ${{ matrix.args }}"
    runs-on: ${{ matrix.runson }}

    container:
      image: ${{ matrix.container }}

    strategy:
      matrix:
        include:

          ##########################################################################################
          # Arch Linux
          ##########################################################################################
          - machine: archlinux.acpp
            container: archlinux/archlinux:base-devel
            runson: ubuntu-latest
            imagename: ArchLinux

    steps:

      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: build syclenv
        shell: bash # In docker container github action default to sh
        run: uv run syclvenv create .yolo archlinux.acpp

      - name: source the syclenv (no prerequisites installed)
        shell: bash # In docker container github action default to sh
        run: eval "$(uv run syclvenv activate .yolo)"

      - name: Install prerequisites through the syclenv
        shell: bash # In docker container github action default to sh
        run: eval "$(uv run syclvenv activate .yolo)" && install_prerequisites

      - name: source the syclenv (prerequisites installed)
        shell: bash # In docker container github action default to sh
        run: eval "$(uv run syclvenv activate .yolo)"